id: IED40F30E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:49:35+00:00'
last_modified: '2022-06-10T05:35:32.575281+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ1547
  title: ལོ་ཙཱ་བ་རིན་ཆེན་བཟང་པོའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7AED:
      image_group_id: I1PD108299
      title: Volume 1 of lo tsA ba rin chen bzang po'i rnam thar/
      total_pages: 32
      order: 1
      base_file: 7AED.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
